openapi: 3.0.3
info:
  title: Retail Simulation API
  version: 1.0.0-SNAPSHOT
paths:
  /simulate:
    summary: Generate sale records
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: string
            examples:
              customer:
                value:
                  customer: 1015
                  count: 5
              random customer:
                value:
                  count: 5
        required: true
      tags:
        - Simulator Resource
      responses:
        '200':
          description: OK
